export const INCREASE_LOADING = 'INCREASE_LOADING';
export const DECREASE_LOADING = 'DECREASE_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const UNSET_ERROR = 'UNSET_ERROR';
export const SET_FORM = 'SET_FORM';
export const SET_BULLET_POINT = 'SET_BULLET_POINT';
export const SET_MAP_AREAS = 'SET_MAP_AREAS';
